
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class homepg extends javax.swing.JFrame {

    DefaultTableModel table;
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;  
    welcpg wel = new welcpg();
    loginpg lip = new loginpg();
   
    
    public void getData(){
       String name = namelbl.getText();
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/bank", "root", "root");
            String checkID = "SELECT STARTING_BALANCE FROM ACCOUNT WHERE EMAIL=? ";
            PreparedStatement ps = con.prepareStatement(checkID);

            ps.setString(1, name);

            ResultSet rs = ps.executeQuery(); // Execute the query

            if(rs.next()){
                String bal = rs.getString("STARTING_BALANCE");
                balance.setText(bal);
            } else {
               System.out.print("O");
            }
        } catch (SQLException ex) {
            Logger.getLogger(homepg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void insertData(){
        String namee = namelbl.getText();
        DefaultTableModel table = new DefaultTableModel();

        try {
            String trans = "SELECT ACCID, MODE, RECORD FROM TRANS WHERE ACCID = ?";
            PreparedStatement ps = con.prepareStatement(trans);
            ps.setString(1, namee);
            ResultSet rs1 = ps.executeQuery();

            transTable.setModel(table);
            table.addColumn("ACCID");
            table.addColumn("MODE");
            table.addColumn("RECORD");

            transTable.setSelectionMode(SINGLE_SELECTION);

            while (rs1.next()) {
                Vector<String> vecuserinfo = new Vector<>();
                vecuserinfo.add(rs1.getString("ACCID"));
                vecuserinfo.add(rs1.getString("MODE"));
                vecuserinfo.add(rs1.getString("RECORD"));
                table.addRow(vecuserinfo);
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); // Handle or log the exception properly
        }
    
    }
    
    public homepg() {
        initComponents();
        wel.DoConnect();
        transaction.setVisible(false);
        cashout.setVisible(false);
        cashin.setVisible(false);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namelbl = new javax.swing.JLabel();
        transaction = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        transTable = new javax.swing.JTable();
        cashin = new javax.swing.JPanel();
        reftxt = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        acc_ID = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        cancel_btn_in = new javax.swing.JButton();
        conf_btn_in = new javax.swing.JButton();
        cashout = new javax.swing.JPanel();
        accnametxt = new javax.swing.JLabel();
        accidtxt = new javax.swing.JLabel();
        ammounttxt = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        cancel_btn_out = new javax.swing.JButton();
        confirm_btn_out = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        btntrans = new javax.swing.JButton();
        bankTransfer = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namelbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        namelbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 320, 40));

        transaction.setBackground(new java.awt.Color(204, 204, 204));
        transaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_btn.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        close_btn.setForeground(new java.awt.Color(204, 0, 51));
        close_btn.setText("CLOSE");
        close_btn.setContentAreaFilled(false);
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        transaction.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        transTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(transTable);

        transaction.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 200));

        getContentPane().add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 410, 200));

        cashin.setBackground(new java.awt.Color(204, 204, 204));
        cashin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reftxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reftxt.setText("REFERENCE NO.");
        cashin.add(reftxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        acc_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acc_name.setText("ACCOUNT NAME");
        cashin.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        acc_ID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        acc_ID.setText("ACCOUNT ID");
        cashin.add(acc_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        amount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        amount.setText("AMOUNT");
        cashin.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        cashin.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, 30));
        cashin.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 30));
        cashin.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 210, 30));
        cashin.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, 30));

        cancel_btn_in.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cancel_btn_in.setForeground(new java.awt.Color(204, 0, 51));
        cancel_btn_in.setText("CANCEL");
        cancel_btn_in.setContentAreaFilled(false);
        cancel_btn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn_inActionPerformed(evt);
            }
        });
        cashin.add(cancel_btn_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        conf_btn_in.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        conf_btn_in.setForeground(new java.awt.Color(0, 51, 153));
        conf_btn_in.setText("CONFIRM");
        conf_btn_in.setContentAreaFilled(false);
        conf_btn_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conf_btn_inActionPerformed(evt);
            }
        });
        cashin.add(conf_btn_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        getContentPane().add(cashin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 410, 200));

        cashout.setBackground(new java.awt.Color(204, 204, 204));
        cashout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accnametxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accnametxt.setText("ACCOUNT NAME");
        cashout.add(accnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        accidtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        accidtxt.setText("ACCOUNT ID");
        cashout.add(accidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        ammounttxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ammounttxt.setText("AMOUNT");
        cashout.add(ammounttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        cashout.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 30));
        cashout.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 210, 30));
        cashout.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, 30));

        cancel_btn_out.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cancel_btn_out.setForeground(new java.awt.Color(204, 0, 51));
        cancel_btn_out.setText("CANCEL");
        cancel_btn_out.setContentAreaFilled(false);
        cancel_btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btn_outActionPerformed(evt);
            }
        });
        cashout.add(cancel_btn_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        confirm_btn_out.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        confirm_btn_out.setForeground(new java.awt.Color(0, 51, 153));
        confirm_btn_out.setText("CONFIRM");
        confirm_btn_out.setContentAreaFilled(false);
        confirm_btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btn_outActionPerformed(evt);
            }
        });
        cashout.add(confirm_btn_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        getContentPane().add(cashout, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 410, 200));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Available Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        balance.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("PHP 00.00");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        exit.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXIT.png"))); // NOI18N
        exit.setText("EXIT");
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 110, 30));

        profile.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PROFILE.png"))); // NOI18N
        profile.setText("PROFILE");
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 150, 30));

        btntrans.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btntrans.setForeground(new java.awt.Color(255, 255, 255));
        btntrans.setText("TRANSACTIONS");
        btntrans.setBorderPainted(false);
        btntrans.setContentAreaFilled(false);
        btntrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransActionPerformed(evt);
            }
        });
        getContentPane().add(btntrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 30));

        bankTransfer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bankTransfer.setForeground(new java.awt.Color(255, 255, 255));
        bankTransfer.setText("Bank Transfer");
        bankTransfer.setBorderPainted(false);
        bankTransfer.setContentAreaFilled(false);
        bankTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTransferActionPerformed(evt);
            }
        });
        getContentPane().add(bankTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 30));

        withdraw.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        withdraw.setForeground(new java.awt.Color(255, 255, 255));
        withdraw.setText("Withdraw");
        withdraw.setBorderPainted(false);
        withdraw.setContentAreaFilled(false);
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepagebg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bankTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankTransferActionPerformed
        cashin.setVisible(true);
        transaction.setVisible(false);
        cashout.setVisible(false);
    }//GEN-LAST:event_bankTransferActionPerformed

    private void btntransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransActionPerformed
       transaction.setVisible(true);
        insertData();
       cashout.setVisible(false);
        cashin.setVisible(false);
    }//GEN-LAST:event_btntransActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        cashout.setVisible(true);
        transaction.setVisible(false);
        cashin.setVisible(false);
    }//GEN-LAST:event_withdrawActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        loginpg lp = new loginpg();
        lp.setVisible(true);   
    }//GEN-LAST:event_exitActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        profilepg prof = new profilepg();
        prof.email.setText(namelbl.getText());
        prof.getProfile();
        prof.setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void cancel_btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn_inActionPerformed
       transaction.setVisible(false);
        cashout.setVisible(false);
        cashin.setVisible(false);
    }//GEN-LAST:event_cancel_btn_inActionPerformed

    private void conf_btn_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conf_btn_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conf_btn_inActionPerformed

    private void confirm_btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btn_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_btn_outActionPerformed

    private void cancel_btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btn_outActionPerformed
        transaction.setVisible(false);
        cashout.setVisible(false);
        cashin.setVisible(false);
    }//GEN-LAST:event_cancel_btn_outActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        transaction.setVisible(false);
        cashout.setVisible(false);
        cashin.setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_ID;
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel accidtxt;
    private javax.swing.JLabel accnametxt;
    private javax.swing.JLabel ammounttxt;
    private javax.swing.JLabel amount;
    private javax.swing.JLabel balance;
    private javax.swing.JButton bankTransfer;
    private javax.swing.JButton btntrans;
    private javax.swing.JButton cancel_btn_in;
    private javax.swing.JButton cancel_btn_out;
    private javax.swing.JPanel cashin;
    private javax.swing.JPanel cashout;
    private javax.swing.JButton close_btn;
    private javax.swing.JButton conf_btn_in;
    private javax.swing.JButton confirm_btn_out;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JLabel namelbl;
    private javax.swing.JButton profile;
    private javax.swing.JLabel reftxt;
    private javax.swing.JTable transTable;
    private javax.swing.JPanel transaction;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
