
import java.awt.Color;
import static java.awt.Color.RED;
import static java.awt.Color.WHITE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author itsme
 */
public class loginpg extends javax.swing.JFrame {
    
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement ps;
    welcpg wel = new welcpg();
    String username;
    String getUserName;
    
    public loginpg() {
        initComponents();
        wel.DoConnect();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closelbl = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        loginbtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closelbl.setForeground(new java.awt.Color(255, 255, 255));
        closelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closelbl.setText("Close");
        closelbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closelbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closelblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closelblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closelblMouseExited(evt);
            }
        });
        getContentPane().add(closelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 70, 20));

        backbtn.setBackground(new java.awt.Color(43, 109, 149));
        backbtn.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbtnMouseExited(evt);
            }
        });
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 70, -1));

        loginbtn1.setBackground(new java.awt.Color(43, 109, 149));
        loginbtn1.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginbtn1.setText("Log In");
        loginbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtn1MouseExited(evt);
            }
        });
        loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 70, -1));

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        pass.setBackground(new java.awt.Color(204, 204, 204));
        pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 200, 30));

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Account ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        email.setBackground(new java.awt.Color(204, 204, 204));
        email.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 200, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clgLogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 80, 80));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg login.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        welcpg wel = new welcpg();
        this.dispose();
        wel.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void backbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseEntered
        backbtn.setBackground(new Color(0,153,153));
        backbtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_backbtnMouseEntered

    private void backbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseExited
        backbtn.setBackground(new Color(43,109,149));
        backbtn.setForeground(new Color(222,222,222));
    }//GEN-LAST:event_backbtnMouseExited

    private void closelblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closelblMouseClicked

    private void loginbtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseEntered
        backbtn.setBackground(new Color(0,153,153));
        backbtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_loginbtn1MouseEntered

    private void loginbtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtn1MouseExited
        backbtn.setBackground(new Color(43,109,149));
        backbtn.setForeground(new Color(222,222,222));
    }//GEN-LAST:event_loginbtn1MouseExited

    private void loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtn1ActionPerformed

        homepg home = new homepg();
        home.namelbl.setText(email.getText());
        home.getData();
        username = email.getText();        
        String passWord = pass.getText();

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/bank", "root", "root");
            String login = "SELECT EMAIL, PASSWORD FROM LOGIN_INFO WHERE EMAIL=? AND PASSWORD=?";
            PreparedStatement ps = con.prepareStatement(login); // Prepare the statement

            ps.setString(1, username);
            ps.setString(2, passWord);
            ResultSet rs = ps.executeQuery(); // Execute the query

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Log In Successfully!");
                
                rs.close();
                ps.close();
                con.close();
                this.dispose();
                
                home.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Log In Failed [Incorrect Email or Password]");
            }
        } catch (SQLException ex) {
            Logger.getLogger(loginpg.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_loginbtn1ActionPerformed

    private void closelblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseEntered
       closelbl.setForeground(RED);
    }//GEN-LAST:event_closelblMouseEntered

    private void closelblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelblMouseExited
         closelbl.setForeground(WHITE);
    }//GEN-LAST:event_closelblMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel closelbl;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginbtn1;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
