
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author itsme
 */
public class profilepg extends javax.swing.JFrame {
    welcpg wel = new welcpg();
    
     Connection con;
     Statement st;
     ResultSet rs;
    /**
     * Creates new form profilepg
     */
    public void getProfile(){
        String username = email.getText();
     
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/bank", "root", "root");
            String checkID = "SELECT ACCID,ACCHL,BIRTHDATE,CONTACTNO FROM ACCOUNT WHERE EMAIL=? ";
            PreparedStatement ps = con.prepareStatement(checkID);

            ps.setString(1, username);

            ResultSet rs = ps.executeQuery(); // Execute the query

            if(rs.next()){
                accID.setText(rs.getString("ACCID"));
                accHL.setText(rs.getString("ACCHL"));
                //rs.getString("STARTING_BALANCE"));
                birthday.setText(rs.getString("BIRTHDATE"));
                contno.setText(rs.getString("CONTACTNO"));
            } else {
               System.out.print("O");
            }
        } catch (SQLException ex) {
            Logger.getLogger(homepg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    public profilepg() {
        wel.DoConnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthday = new javax.swing.JTextField();
        accHL = new javax.swing.JTextField();
        accID = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        contno = new javax.swing.JTextField();
        closeBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(650, 380));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, 30));
        getContentPane().add(accHL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 140, 30));
        getContentPane().add(accID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, 30));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 180, 30));
        getContentPane().add(contno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 140, 30));

        closeBTN.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        closeBTN.setForeground(new java.awt.Color(204, 204, 204));
        closeBTN.setText("Close");
        closeBTN.setContentAreaFilled(false);
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 40));

        jButton2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Confirm Change");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, 40));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 120, -1));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Change Password");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profilepg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        this.dispose();
        homepg home = new homepg();
        home.namelbl.setText(email.getText());
        home.getData();
        home.setVisible(true);
    }//GEN-LAST:event_closeBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profilepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profilepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profilepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profilepg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profilepg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField accHL;
    public javax.swing.JTextField accID;
    public javax.swing.JTextField birthday;
    private javax.swing.JButton closeBTN;
    public javax.swing.JTextField contno;
    public javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
