
import static com.sun.javafx.scene.control.skin.FXVK.Type.EMAIL;
import static java.lang.System.err;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author itsme
 */
public class registerpg extends javax.swing.JFrame {

     Connection con;
     Statement st;
     ResultSet rs;
     welcpg wel = new welcpg();
    
    PreparedStatement ps;
     
    public void register() {
    try {
        String confirm_password = conpwtxt.getText();
        String first_password = pwtxt.getText();

        if (!first_password.equals(confirm_password)){
            JOptionPane.showMessageDialog(null, "Password is not the same");
        }else{
            // Establish connection
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/bank", "root", "root");
            // SQL query to insert data
            String add = "INSERT INTO account (ACCID,ACCHL,STARTING_BALANCE,BIRTHDATE,CONTACTNO,EMAIL,PASSWORD) VALUES (?, ?, ?, ?, ?, ?, ?)";
            // Prepare the PreparedStatement with the SQL query
            PreparedStatement ps = con.prepareStatement(add);
            // Set parameters for the PreparedStatement
            ps.setString(1, accID.getText());
            ps.setString(2, accHl.getText());
            ps.setString(3, balance.getText());
            ps.setString(4, bdate.getText());
            ps.setString(5, contactno.getText());
            ps.setString(6, emailtxt.getText());
            ps.setString(7, pwtxt.getText());
            // Execute the update
            int rowsAffected = ps.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Registration successful!");
                ps.close();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registration failed!");
            }
        }
    } catch (SQLException ex) {
        System.out.println(ex.getMessage());
    }
}
    public void register2() {
    try {
        String confirm_password = conpwtxt.getText();
          String first_password = pwtxt.getText();
        if (!first_password.equals(confirm_password)){
                System.out.println("not same password");
      }else{
        
        con = DriverManager.getConnection("jdbc:derby://localhost:1527/bank", "root", "root");
        String add2 = "INSERT INTO LOGIN_INFO (ACCID, EMAIL, PASSWORD) VALUES (?, ?, ?)";
        
        PreparedStatement ps2 = con.prepareStatement(add2);
        
        ps2.setString(1, accID.getText());
        ps2.setString(2, emailtxt.getText());
        ps2.setString(3, pwtxt.getText());
        
        int rowsAffected2 = ps2.executeUpdate();;
            if (rowsAffected2 > 0) {
            System.out.println("Registration Successful");
            ps2.close();
            
            }
         else {
             System.out.println("Registration failed");
        }
        }
        
    } catch (SQLException ex) {
        System.err.println(ex.getMessage());
    }
}    
    public registerpg() {
        initComponents();
        wel.DoConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notsamepw = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        conpwtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        pwtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        reg = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        accHl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        accID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(403, 505));
        setSize(new java.awt.Dimension(403, 505));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notsamepw.setForeground(new java.awt.Color(255, 255, 255));
        notsamepw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(notsamepw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 20));

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Confirm Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        conpwtxt.setBackground(new java.awt.Color(204, 204, 204));
        conpwtxt.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        conpwtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(conpwtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 30));

        jLabel8.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Contact Number:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        contactno.setBackground(new java.awt.Color(204, 204, 204));
        contactno.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        contactno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 30));

        emailtxt.setBackground(new java.awt.Color(204, 204, 204));
        emailtxt.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        emailtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, 30));

        pwtxt.setBackground(new java.awt.Color(204, 204, 204));
        pwtxt.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        pwtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(pwtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 30));

        jLabel10.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Birthdate:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        bdate.setBackground(new java.awt.Color(204, 204, 204));
        bdate.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        bdate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cancel");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        reg.setBackground(new java.awt.Color(55, 133, 186));
        reg.setText("Register");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        loginbtn.setBackground(new java.awt.Color(55, 133, 186));
        loginbtn.setText("Log in");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 70, -1));

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Starting Balance:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        balance.setBackground(new java.awt.Color(204, 204, 204));
        balance.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 30));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Account Holder:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        accHl.setBackground(new java.awt.Color(204, 204, 204));
        accHl.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        accHl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(accHl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Account ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        accID.setBackground(new java.awt.Color(204, 204, 204));
        accID.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        accID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(accID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clgLogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        if (accID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Account ID is required.");
        } else if (accHl.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Account Holder is required.");
        }else if (balance.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Starting Balance is required.");
        }else if (bdate.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Birthdate is required.");
        }else if (contactno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Contact Number is required.");
        }else if (emailtxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Email is required.");
        }else if (pwtxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Password is required.");
        }else{
        register();
        register2();
        }
    }//GEN-LAST:event_regActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        welcpg w = new welcpg();
        w.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
         this.dispose();
  loginpg lgp = new loginpg();
    lgp.setVisible(true);
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accHl;
    private javax.swing.JTextField accID;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField bdate;
    private javax.swing.JTextField conpwtxt;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel notsamepw;
    private javax.swing.JTextField pwtxt;
    private javax.swing.JButton reg;
    // End of variables declaration//GEN-END:variables
}
